# Generated by Django 6.0.7 on 2026-07-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlement',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
